title = "noRth 2019 Conference"
baseURL = "https://rnorthconference.github.io/"
relativeURL= true
tags = ["conference", "R", "programming"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../rnorthconference.github.io"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
  tagline = "A conference for R users in the Twin Cities and greater north region"
  author = "Lindsey Dietz"
  description = ""
  logoBig = "/images/noRth2019.png" 
  logoSmall = "/images/north.jpg"
  favicon = "favicon.ico"
  opengraphImage = "/images/noRth2019.png"
  email = "rnorthconf@gmail.com"
  googleTagManger = ""
  customCSS = true

  # Social media links in footer
  twitter = ""
  linkedin = ""
  github = "" #"rnorthconference"
  facebook = ""

  # Copyright and theme author credit in footer
  copyright = false
  credit = false

  # Cache busting of static resources (additional set up required)
  cacheBustCSS = false
  cacheBustJS = false

  # Code highlighting with highlight.js
  highlightJS = true
  highlightJSStyle = "" # For custom highlight.js styles, add your /path/to/styles/default.css
  highlightJSScript = "" # For custom highlight.js languages config, add your /path/to/highlight.pack.js

  # Choose either Formspree contact form or Basin contact form
  ajaxFormspree = true
  ajaxFormspreeGold = false
  ajaxBasin = ""

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Speakers"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Conduct"
  url  = "/#blog"
  weight = 3
[[menu.main]]
  name = "Registration"
  url  = "/#contact"
  weight = 4